# Netlify configuration for Next.js project

[build]
  command = "npm run build"
  base = ""

[build.environment]
  NODE_VERSION = "20.13.1"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Cache static assets for faster loads
[[headers]]
  for = "/_next/static/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/api/*"
    [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"

# Redirects to Next.js function (only if SSR is used)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200
