# netlify.toml

[build]
  # Base directory is the repository root (no need to change this if your project files are in the root)
  base = ""

  # Directory that contains the deploy-ready HTML files and assets.
  publish = "build"

  # Default build command.
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20.13.1"

# Production context: All deploys from the main
# repository branch will inherit these settings.
[context.production]
  command = "npm run build"

# Deploy Preview context: 
# All deploys resulting from a pull/merge request
# will inherit these settings.
[context.deploy-preview]
  command = "npm run build:preview"

# Branch deploy context: All deploys that are not from
# a pull/merge request or from the production branch
# will inherit these settings.
[context.branch-deploy]
  command = "npm run build:branch"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers to set on specific paths
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Asset optimization
[build.processing]
  skip_processing = false